# Generated by Django 5.2.17 on 2026-09-20 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('recommendation_type', models.CharField(choices=[('BOTTLENECK', 'Bottleneck'), ('ANOMALY', 'Anomaly'), ('PREDICTION', 'Prediction'), ('DATA_QUALITY', 'Data Quality'), ('PROCESS', 'Process Improvement'), ('CAPACITY', 'Capacity'), ('AUTOMATION', 'Automation'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWED', 'Reviewed'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], default='NEW', max_length=20)),
                ('evidence', models.JSONField(blank=True, default=dict)),
                ('expected_impact', models.TextField(blank=True)),
                ('ai_explanation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='organizations.organization')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='workflows.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'workflow'], name='recommendat_organiz_3914c6_idx'), models.Index(fields=['organization', 'priority'], name='recommendat_organiz_32c7da_idx'), models.Index(fields=['organization', 'status'], name='recommendat_organiz_b75f8f_idx'), models.Index(fields=['organization', 'recommendation_type'], name='recommendat_organiz_ae881d_idx')],
            },
        ),
    ]
