# Generated by Django 5.2.17 on 2026-09-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('recommendations', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-score', '-created_at']},
        ),
        migrations.AddField(
            model_name='recommendation',
            name='evidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='impact_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='severity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddIndex(
            model_name='recommendation',
            index=models.Index(fields=['organization', 'score'], name='recommendat_organiz_892eb6_idx'),
        ),
    ]
