# Generated by Django 5.2.17 on 2026-09-20 15:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('workload_change_percent', models.FloatField(default=0.0, help_text='Percentage change in workload compared with the baseline.', validators=[django.core.validators.MinValueValidator(-100.0)])),
                ('baseline_event_count', models.PositiveIntegerField(default=0)),
                ('projected_event_count', models.PositiveIntegerField(default=0)),
                ('baseline_avg_duration', models.FloatField(default=0.0)),
                ('projected_avg_duration', models.FloatField(default=0.0)),
                ('baseline_total_duration', models.FloatField(default=0.0)),
                ('projected_total_duration', models.FloatField(default=0.0)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('results', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='organizations.organization')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulations', to='workflows.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='sim_org_created_idx'), models.Index(fields=['organization', 'workflow'], name='sim_org_workflow_idx'), models.Index(fields=['status'], name='sim_status_idx')],
            },
        ),
    ]
