from apps.recommendations.models import Recommendation

from ..models import Notification
from .notification_service import NotificationService


class RecommendationNotificationService:
    """
    Creates notifications for recommendations generated by FlowMind AI.
    """

    PRIORITY_MAP = {
        Recommendation.Priority.LOW: Notification.Priority.LOW,
        Recommendation.Priority.MEDIUM: Notification.Priority.MEDIUM,
        Recommendation.Priority.HIGH: Notification.Priority.HIGH,
        Recommendation.Priority.CRITICAL: Notification.Priority.CRITICAL,
    }

    @classmethod
    def create_for_recommendation(
        cls,
        *,
        recommendation,
        recipient=None,
    ):
        if not isinstance(recommendation, Recommendation):
            raise ValueError(
                "A valid Recommendation instance is required."
            )

        priority = cls.PRIORITY_MAP.get(
            recommendation.priority,
            Notification.Priority.MEDIUM,
        )

        workflow = recommendation.workflow

        return NotificationService.create(
            organization=recommendation.organization,
            recipient=recipient,
            workflow=workflow,
            notification_type=Notification.NotificationType.RECOMMENDATION,
            priority=priority,
            title=recommendation.title,
            message=recommendation.description,
            related_object_type="recommendation",
            related_object_id=recommendation.id,
        )