# Generated by Django 5.2.17 on 2026-09-21 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('VIEW', 'View'), ('EXPORT', 'Export'), ('GENERATE', 'Generate'), ('RUN', 'Run'), ('OTHER', 'Other')], max_length=20)),
                ('object_type', models.CharField(max_length=100)),
                ('object_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='audit_audit_organiz_c1c99d_idx'), models.Index(fields=['user', '-created_at'], name='audit_audit_user_id_429f6b_idx'), models.Index(fields=['organization', 'action'], name='audit_audit_organiz_775090_idx'), models.Index(fields=['organization', 'object_type'], name='audit_audit_organiz_71a128_idx')],
            },
        ),
    ]
