# Generated by Django 5.2.17 on 2026-09-20 12:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('OPERATIONS', 'Operations'), ('ORDER_FULFILLMENT', 'Order Fulfillment'), ('CUSTOMER_SERVICE', 'Customer Service'), ('FINANCE', 'Finance'), ('HUMAN_RESOURCES', 'Human Resources'), ('IT', 'IT'), ('SALES', 'Sales'), ('OTHER', 'Other')], default='OPERATIONS', max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='organizations.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('expected_duration', models.DecimalField(blank=True, decimal_places=2, help_text='Expected duration in minutes.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('department', models.CharField(blank=True, max_length=255)),
                ('responsible_role', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflows.workflow')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(blank=True, help_text='Optional business condition for this transition.', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='workflows.workflow')),
                ('source_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_connections', to='workflows.workflowstep')),
                ('target_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_connections', to='workflows.workflowstep')),
            ],
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['organization', 'status'], name='workflows_w_organiz_867754_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['organization', 'category'], name='workflows_w_organiz_a94097_idx'),
        ),
        migrations.AddIndex(
            model_name='workflow',
            index=models.Index(fields=['organization', 'created_at'], name='workflows_w_organiz_6faac8_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflow',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_workflow_name_per_organization'),
        ),
        migrations.AddIndex(
            model_name='workflowstep',
            index=models.Index(fields=['workflow', 'order'], name='workflows_w_workflo_394b33_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowstep',
            index=models.Index(fields=['workflow', 'department'], name='workflows_w_workflo_d7e0c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowstep',
            constraint=models.UniqueConstraint(fields=('workflow', 'order'), name='unique_step_order_per_workflow'),
        ),
        migrations.AddConstraint(
            model_name='workflowstep',
            constraint=models.UniqueConstraint(fields=('workflow', 'name'), name='unique_step_name_per_workflow'),
        ),
        migrations.AddIndex(
            model_name='workflowconnection',
            index=models.Index(fields=['workflow'], name='workflows_w_workflo_d6f7b6_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowconnection',
            index=models.Index(fields=['source_step'], name='workflows_w_source__d8ee2b_idx'),
        ),
        migrations.AddIndex(
            model_name='workflowconnection',
            index=models.Index(fields=['target_step'], name='workflows_w_target__981fef_idx'),
        ),
        migrations.AddConstraint(
            model_name='workflowconnection',
            constraint=models.UniqueConstraint(fields=('workflow', 'source_step', 'target_step'), name='unique_workflow_connection'),
        ),
    ]
