# Generated by Django 5.2.17 on 2026-09-20 16:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(1)])),
                ('description', models.TextField(blank=True)),
                ('report_type', models.CharField(choices=[('WORKFLOW_SUMMARY', 'Workflow Summary'), ('ANALYTICS', 'Analytics'), ('BOTTLENECK', 'Bottleneck Analysis'), ('ANOMALY', 'Anomaly Analysis'), ('PREDICTION', 'Prediction Analysis'), ('RECOMMENDATION', 'Recommendation Report'), ('SIMULATION', 'Simulation Report'), ('AI_INSIGHT', 'AI Insight'), ('CUSTOM', 'Custom Report')], default='WORKFLOW_SUMMARY', max_length=40)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='DRAFT', max_length=20)),
                ('output_format', models.CharField(choices=[('HTML', 'HTML'), ('JSON', 'JSON'), ('PDF', 'PDF'), ('CSV', 'CSV')], default='HTML', max_length=10)),
                ('content', models.TextField(blank=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='organizations.organization')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='workflows.workflow')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='report_org_created_idx'), models.Index(fields=['organization', 'status'], name='report_org_status_idx'), models.Index(fields=['organization', 'report_type'], name='report_org_type_idx'), models.Index(fields=['organization', 'workflow'], name='report_org_workflow_idx')],
            },
        ),
    ]
