# Generated by Django 5.2.17 on 2026-09-20 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('WORKFLOW', 'Workflow'), ('DATASET', 'Dataset'), ('REPORT', 'Report'), ('MANUAL', 'Manual'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_documents', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.PositiveIntegerField()),
                ('content', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_engine.knowledgedocument')),
            ],
            options={
                'ordering': ['chunk_index'],
            },
        ),
        migrations.AddIndex(
            model_name='knowledgedocument',
            index=models.Index(fields=['organization', 'source_type'], name='ai_engine_k_organiz_a2be71_idx'),
        ),
        migrations.AddIndex(
            model_name='knowledgechunk',
            index=models.Index(fields=['document', 'chunk_index'], name='ai_engine_k_documen_2c256b_idx'),
        ),
        migrations.AddConstraint(
            model_name='knowledgechunk',
            constraint=models.UniqueConstraint(fields=('document', 'chunk_index'), name='unique_document_chunk_index'),
        ),
    ]
