# Generated by Django 5.2.17 on 2026-09-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgechunk',
            name='embedding',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
